FROM grafana/grafana-enterprise

COPY /grafana /etc/grafana

RUN grafana-cli plugins install grafana-piechart-panel

# Disable Login form or not
ENV GF_AUTH_DISABLE_LOGIN_FORM "true"
# Allow anonymous authentication or not
ENV GF_AUTH_ANONYMOUS_ENABLED "true"
# Role of anonymous user
ENV GF_AUTH_ANONYMOUS_ORG_ROLE "Admin"

