version: '3.8'

services:
  procat-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procat-server
    restart: unless-stopped
    depends_on:
      - procat-db
    volumes:
      - procat_assets:/go/assets
    ports:
      - "${BIND_ADDR}:${BIND_ADDR}"
    networks:
      - appnet
      - internet

  procat-db:
    image: postgres
    container_name: procat-db
    restart: unless-stopped
    volumes:
      - procat_db_tmp:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_NAME}", "-p", "${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - "${DB_PORT}"
    command: -p ${DB_PORT}
    networks:
      - appnet

volumes:
  procat_db_tmp:
  procat_assets:

networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: appnet
    driver: bridge
