version: '3.8'

services:
  procat-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procat-server
    restart: unless-stopped
    depends_on:
      - procat-db
    volumes:
      - procat_assets:/go/assets
    ports:
      - "${BIND_ADDR}:${BIND_ADDR}"
    networks:
      - appnet
      - internet

  procat-db:
    image: postgres
    container_name: procat-db
    restart: unless-stopped
    volumes:
      - procat_db_tmp:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_NAME}", "-p", "${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - "${DB_PORT}"
    command: -p ${DB_PORT}
    networks:
      - appnet

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile_prometheus
    container_name: prometheus-service
    restart: unless-stopped
    user: root
    depends_on:
      - procat-server
    ports:
      - "${PROMETHEUS_BIND_ADDR}:9090"
    volumes:
      - prometheus_storage:/prometheus
    networks:
      - appnet

  grafana:
    build:
      context: .
      dockerfile: Dockerfile_grafana
    container_name: grafana-service
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - grafana_storage:/var/lib/grafana
    ports:
      - "${GRAFANA_BIND_ADDR}:3000"
    networks:
      - appnet
      - internet

volumes:
  procat_db_tmp:
  procat_assets:
  prometheus_storage:
  grafana_storage:

networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: appnet
    driver: bridge
