global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'procat_server'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['procat-server:8081']