openapi: 3.0.3
info:
  title: ProCat
  description: |-
    OpenAPI documentation for ProCat application
  version: 1.0.0
servers:
  - url: 'localhost:8080'
paths:

#TODO: переписать компоненты, так как схема поменялась
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fullName:
          type: string
        email:
          type: string
        phone_number:
          type: string
        identification_number:
          type: string
        password_hash:
          type: string
        is_confirmed:
          type: boolean
        role:
          type: string
        created_at:
          type: string
          format: date-time

    DeliveryMan:
      type: object
      properties:
        id:
          type: integer
          format: int64
        car_capacity:
          type: string
        working_hours_start:
          type: string
          format: time
        working_hours_end:
          type: string
          format: time
        car_id:
          type: string
        user_id:
          type: integer
          format: int64

    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
        total_price:
          type: integer
        rental_period_start:
          type: string
          format: date-time
        rental_period_end:
          type: string
          format: date-time
        address:
          type: string
        company_name:
          type: string
        user_id:
          type: integer
          format: int64

    Delivery:
      type: object
      properties:
        id:
          type: integer
          format: int64
        time:
          type: string
          format: date-time
        method:
          type: string
        order_id:
          type: integer
          format: int64
        delivery_man_id:
          type: integer
          format: int64

    Payment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        is_paid:
          type: boolean
        method:
          type: string
        price:
          type: integer
        order_id:
          type: integer
          format: int64

    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        parent_id:
          type: integer
          format: int64

    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        price:
          type: integer
        category_id:
          type: integer
          format: int64

    ItemStatus:
      type: object
      properties:
        id:
          type: integer
          format: int64
        is_in_stock:
          type: boolean
        in_stock_number:
          type: integer
        address:
          type: string
        item_id:
          type: integer
          format: int64

    ItemImage:
      type: object
      properties:
        id:
          type: integer
          format: int64
        image:
          type: string
        item_id:
          type: integer
          format: int64

    OrderItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        items_number:
          type: integer
        order_id:
          type: integer
          format: int64
        item_id:
          type: integer
          format: int64

    Info:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        item_id:
          type: integer
          format: int64

    Cart:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64

    CartItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        items_number:
          type: integer
        cart_id:
          type: integer
          format: int64
        item_id:
          type: integer
          format: int64

    Subscription:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64

    SubscriptionItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        subscription_id:
          type: integer
          format: int64
        item_id:
          type: integer
          format: int64

    Notification:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        is_viewed:
          type: boolean
        user_id:
          type: integer
          format: int64

    Chat:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        is_solved:
          type: boolean
        first_user_id:
          type: integer
          format: int64
        second_user_id:
          type: integer
          format: int64
        order_id:
          type: integer
          format: int64

    Message:
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        user_id:
          type: integer
          format: int64
        chat_id:
          type: integer
          format: int64

    MessageImage:
      type: object
      properties:
        id:
          type: integer
          format: int64
        image:
          type: string
        message_id:
          type: integer
          format: int64

  
