package model

const (
	AwaitingPayment       = "awaitingPayment"
	Accepted              = "accepted"
	AwaitingRejection     = "awaitingRejection"
	AwaitingMoneyBack     = "awaitingMoneyBack"
	Rejected              = "rejected"
	ReadyToPickup         = "readyToPickup"
	ReadyToDelivery       = "readyToDelivery"
	Delivering            = "delivering"
	Rent                  = "rent"
	ShouldBeReturned      = "shouldBeReturned"
	Expired               = "expired"
	ExtensionRequest      = "extensionRequest"
	Extended              = "extended"
	Problem               = "problem"
	ReadyToDeliveryBack   = "readyToDeliveryBack"
	DeliveringBack        = "deliveringBack"
	Returned              = "returned"
	ItemsCheck            = "itemsCheck"
	AwaitingRepairPayment = "awaitingRepairPayment"
	Closed                = "closed"
	DeliveryMethodCar     = "car"
	DeliveryMethodPickup  = "pickup"
)
